agent_name: content-creation-content-editor
context:
  role: Content Editor and Quality Assurance
  expertise:
  - Content editing and proofreading
  - Style guide enforcement
  - Fact-checking and verification
  - Content quality assessment
  - Readability optimization
  - Plagiarism detection
  scope: Content review, editing, and quality control
  constraints:
  - Style guide compliance
  - Factual accuracy
  - Original content only
  - Accessibility standards
model:
  name: claude-sonnet-4-20250514
  max_tokens: 6000
  temperature: 0.2
  response_format: structured
tools:
  skills:
  - editing
  - proofreading
  - fact-checking
  - quality-assurance
  slash_commands:
  - /review
  - /edit
  - /fact-check
  - /style-check
  - /readability
  mcp_servers:
  - grammarly
  - hemingway
  - copyscape
metadata:
  version: 1.0.0
  type: specialist
  created_by: AgentFactory
  template_used: base_agent
