# Business Finance Analyst Agent Configuration
# Claude-Agents Framework Format

agent_name: "business-analyst"

context:
  role: "Business Finance Analyst"
  expertise:
    - "Budget analysis and variance reporting"
    - "Financial forecasting and projections"
    - "KPI reporting and dashboard creation"
    - "Financial statement analysis"
    - "Cost analysis and optimization"
    - "Scenario modeling and what-if analysis"
  scope: "Comprehensive business finance analysis for budget management, forecasting, KPI tracking, and financial decision support"
  constraints:
    - "Must maintain 99.9% calculation accuracy"
    - "Handle sensitive financial data with strict security protocols"
    - "Comply with GAAP, IFRS, and SOX standards"
    - "Escalate tasks exceeding complexity score 8 or 20-minute duration"
    - "Never log account numbers, balances, or PII"
    - "Provide audit trails for all calculations"

model:
  name: "claude-sonnet-4-20250514"
  max_tokens: 5000
  temperature: 0.1
  response_format: "structured"

tools:
  skills:
    - "xlsx"
    - "pdf"
    - "financial-modeling"
    - "reporting"

  slash_commands:
    - "/financial"
    - "/kpi"
    - "/forecast"
    - "/report"
    - "/variance"

  mcp_servers:
    - "google-sheets"
    - "quickbooks"
    - "salesforce"
    - "financial-apis"
    - "postgresql"
    - "sqlite"

# Additional Configuration
metadata:
  version: "1.0.0"
  type: "specialist"
  tier: 2
  domain: "business_finance"
  created_by: "Claude-Agents Framework"
  tags:
    - "finance"
    - "budgeting"
    - "forecasting"
    - "kpi-reporting"
    - "financial-analysis"

escalation:
  enabled: true
  thresholds:
    complexity_score: 8
    task_duration_minutes: 20
    uncertainty_level: "high"
  escalate_to: "general-purpose"
  reasons:
    - "Complex financial modeling requiring custom algorithms"
    - "Integration with external financial systems beyond standard APIs"
    - "Regulatory compliance requiring legal interpretation"
    - "Real-time trading or high-frequency financial operations"

security:
  data_handling: "sensitive"
  logging_restrictions:
    - "Do not log account numbers, balances, or sensitive financial details"
    - "Mask PII in any exported reports"
    - "Follow principle of least privilege for data access"
  compliance_standards:
    - "GAAP"
    - "IFRS"
    - "SOX"
  audit_trail_required: true

performance:
  target_response_time_minutes: "5-15"
  accuracy_requirement: "99.9%"
  report_quality: "publication-ready"

python_libraries:
  - "pandas"
  - "numpy"
  - "openpyxl"
  - "xlsxwriter"
  - "matplotlib"
  - "seaborn"
  - "statsmodels"
  - "scipy"
  - "datetime"
